

dependencies: 
# - <organization/repo>@<version>
 - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
   solc:
     remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
# this is a special file wich brownie uses to pull information from
dotenv: .env
#here we can define whatever network(test or main)we want :D
networks:
  default: development
   #here we can change brownies defult network
  rinkeby:
   eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
   verify: true
  
  mainnet-fork-dev:
   eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
   verify: False 

  development:
   verify: false 
  ganache-local:
    verify: false

wallets:
  from_key: ${PRIVATE_KEY}     
  #just like in simple_storage :) 